version: '3.8'
services:
  db:
    image: postgres:16-bookworm
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8090:8080'
