import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { ReactNode } from 'react';

import '../style/globals.css';
import '../style/reset.css';

import { Header } from '@/components';

const inter = Inter({ subsets: ['latin'] });
const popins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Darmawan',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${popins.className}`}>
        <ThemeProvider attribute='class'>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
